name: Unity Native Audio Plugins CI 

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        cmake --version
        version=3.15
        build=3
        mkdir ~/temp
        cd ~/temp
        wget https://cmake.org/files/v$version/cmake-$version.$build-Linux-x86_64.sh
        sudo mkdir /opt/cmake
        sudo sh cmake-$version.$build-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
        sudo rm /usr/local/bin/cmake
        sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
        cmake --version
    - name: build 
      run: |
        cmake --version
        ./ci/bin/build-ubuntu.sh

  build-mac:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: build 
      run: ./ci/bin/build-mac.sh
